### ISSUE TITLE
Viết chương trình nhập 2 ký tự c1, c2 (giả sử c1, c2 là các ký tự viết thường nằm trong khoảng từ `a' đến `z') và số nguyên x (65 ≤ x ≤ 90). In ra màn hình:  Mã ASCII của ký tự c1 và c2 Khoảng cách giữa 2 ký tự c1 và c2 (tính khoảng cách dựa trên thứ tự trong bảng chữ cái) Dạng viết hoa của ký tự c1 Ký tự có mã ASCII là x

### ISSUE THREAD

**Issue by thaikhiem1** [phanxuanquang/Object-Oriented-Programming-UIT#2]
Viết chương trình nhập 2 ký tự c1, c2 (giả sử c1, c2 là các ký tự viết thường nằm trong khoảng từ `a' đến `z') và số nguyên x (65 ≤ x ≤ 90). In ra màn hình:

Mã ASCII của ký tự c1 và c2
Khoảng cách giữa 2 ký tự c1 và c2 (tính khoảng cách dựa trên thứ tự trong bảng chữ cái)
Dạng viết hoa của ký tự c1
Ký tự có mã ASCII là x
c++

**Comment by phanxuanquang** [comment]
Chào bạn, đây không phải là nơi hỏi bài tập nhé
